[ACK-ACK]
clsID = 5
msgID = 1

[[ACK-ACK.fields]]
format = "U1"
name = "clsID"

[[ACK-ACK.fields]]
format = "U1"
name = "msgID"


[ACK-NAK]
clsID = 5
msgID = 0

[[ACK-NAK.fields]]
format = "U1"
name = "clsID"

[[ACK-NAK.fields]]
format = "U1"
name = "msgID"


[NAV-SVINFO]
clsID = 1
msgID = 48

[[NAV-SVINFO.fields]]
format = "U4"
name = "iTOW"

[[NAV-SVINFO.fields]]
format = "U1"
name = "numCh"

[[NAV-SVINFO.fields]]
format = "X1"
name = "globalFlags"

[[NAV-SVINFO.fields.bitfield]]
name = "chipGen"
range = [ 2, 0,]

[NAV-SVINFO.fields.bitfield.map]
0 = "Antaris 4"
1 = "u-blox 5"
2 = "u-blox 6"
3 = "u-blox 7"
4 = "u-blox 8 / M8"

[[NAV-SVINFO.fields]]
format = "U1[2]"
name = "reserved1"

[[NAV-SVINFO.fields]]
format = "U1[348]"
name = "UNIMPLEMENTED"


[CFG-RATE]
clsID = 6
msgID = 8

[[CFG-RATE.fields]]
format = "U2"
name = "measRate"

[[CFG-RATE.fields]]
format = "U2"
name = "navRate"

[[CFG-RATE.fields]]
format = "U2"
name = "timeRef"


[CFG-MSG]
clsID = 6
msgID = 1

[[CFG-MSG.fields]]
format = "U1"
name = "cls_id"

[[CFG-MSG.fields]]
format = "U1"
name = "msgID"

[[CFG-MSG.fields]]
format = "U1[6]"
name = "rate"


[CFG-CFG]
clsID = 6
msgID = 9

[[CFG-CFG.fields]]
format = "X4"
name = "clearMask"

[[CFG-CFG.fields.bitfield]]
name = "ioPort"
range = 0

[[CFG-CFG.fields.bitfield]]
name = "msgConf"
range = 1

[[CFG-CFG.fields.bitfield]]
name = "infMsg"
range = 2

[[CFG-CFG.fields.bitfield]]
name = "navConf"
range = 3

[[CFG-CFG.fields.bitfield]]
name = "rxmConf"
range = 4

[[CFG-CFG.fields.bitfield]]
name = "senConf"
range = 8

[[CFG-CFG.fields.bitfield]]
name = "rinvConf"
range = 9

[[CFG-CFG.fields.bitfield]]
name = "antConf"
range = 10

[[CFG-CFG.fields.bitfield]]
name = "logConf"
range = 11

[[CFG-CFG.fields.bitfield]]
name = "ftsConf"
range = 12

[[CFG-CFG.fields]]
format = "X4"
name = "saveMask"

[[CFG-CFG.fields.bitfield]]
name = "ioPort"
range = 0

[[CFG-CFG.fields.bitfield]]
name = "msgConf"
range = 1

[[CFG-CFG.fields.bitfield]]
name = "infMsg"
range = 2

[[CFG-CFG.fields.bitfield]]
name = "navConf"
range = 3

[[CFG-CFG.fields.bitfield]]
name = "rxmConf"
range = 4

[[CFG-CFG.fields.bitfield]]
name = "senConf"
range = 8

[[CFG-CFG.fields.bitfield]]
name = "rinvConf"
range = 9

[[CFG-CFG.fields.bitfield]]
name = "antConf"
range = 10

[[CFG-CFG.fields.bitfield]]
name = "logConf"
range = 11

[[CFG-CFG.fields.bitfield]]
name = "ftsConf"
range = 12

[[CFG-CFG.fields]]
format = "X4"
name = "loadMask"

[[CFG-CFG.fields.bitfield]]
name = "ioPort"
range = 0

[[CFG-CFG.fields.bitfield]]
name = "msgConf"
range = 1

[[CFG-CFG.fields.bitfield]]
name = "infMsg"
range = 2

[[CFG-CFG.fields.bitfield]]
name = "navConf"
range = 3

[[CFG-CFG.fields.bitfield]]
name = "rxmConf"
range = 4

[[CFG-CFG.fields.bitfield]]
name = "senConf"
range = 8

[[CFG-CFG.fields.bitfield]]
name = "rinvConf"
range = 9

[[CFG-CFG.fields.bitfield]]
name = "antConf"
range = 10

[[CFG-CFG.fields.bitfield]]
name = "logConf"
range = 11

[[CFG-CFG.fields.bitfield]]
name = "ftsConf"
range = 12

[[CFG-CFG.fields]]
format = "X1"
name = "deviceMask"

[[CFG-CFG.fields.bitfield]]
name = "deviceDevBbr"
range = 0

[[CFG-CFG.fields.bitfield]]
name = "deviceDevFlash"
range = 1

[[CFG-CFG.fields.bitfield]]
name = "deviceDevEeprom"
range = 2

[[CFG-CFG.fields.bitfield]]
name = "deviceDeviceSpiFlash"
range = 4



[CFG-RST]
clsID = 6
msgID = 4
skip_response = true

[[CFG-RST.fields]]
format = "X2"
name = "navBbrMask"

[[CFG-RST.fields.bitfield]]
name = "eph"
range = 0


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Ephemeris"

[[CFG-RST.fields.bitfield]]
name = "alm"
range = 1


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Almanac"

[[CFG-RST.fields.bitfield]]
name = "health"
range = 2


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Health"

[[CFG-RST.fields.bitfield]]
name = "klob"
range = 3


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Klobuchar parameters"

[[CFG-RST.fields.bitfield]]
name = "pos"
range = 4


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Position"

[[CFG-RST.fields.bitfield]]
name = "clkd"
range = 5


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Clock drift"

[[CFG-RST.fields.bitfield]]
name = "osc"
range = 6


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Oscillator parameter"

[[CFG-RST.fields.bitfield]]
name = "utc"
range = 7


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "UTC correction + GPS leap seconds parameters"

[[CFG-RST.fields.bitfield]]
name = "rtc"
range = 8


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "RTC"

[[CFG-RST.fields.bitfield]]
name = "aop"
range = 15


[CFG-RST.fields.bitfield.map]
0 = ""
1 = "Autonomous orbit parameters"

[[CFG-RST.fields]]
format = "U1"
name = "resetMode"

[[CFG-RST.fields]]
format = "U1"
name = "reserved1"


[CFG-NMEA]
clsID = 6
msgID = 23

[[CFG-NMEA.fields]]
format = "X1"
name = "filter"

[[CFG-NMEA.fields.bitfield]]
name = "posFilt"
range = 0

[[CFG-NMEA.fields.bitfield]]
name = "mskPosFilt"
range = 1

[[CFG-NMEA.fields.bitfield]]
name = "timeFilt"
range = 2

[[CFG-NMEA.fields.bitfield]]
name = "dateFilt"
range = 3

[[CFG-NMEA.fields.bitfield]]
name = "gpsOnlyFilter"
range = 4

[[CFG-NMEA.fields.bitfield]]
name = "trackFilt"
range = 5

[[CFG-NMEA.fields]]
format = "U1"
name = "nmeaVersion"

[[CFG-NMEA.fields]]
format = "U1"
name = "numSV"

[[CFG-NMEA.fields]]
format = "X1"
name = "flags"

[[CFG-NMEA.fields.bitfield]]
name = "compat"
range = 0

[[CFG-NMEA.fields.bitfield]]
name = "consider"
range = 1



[CFG-PMS]
clsID = 6
msgID = 134

[[CFG-PMS.fields]]
format = "U1"
name = "version"
doc = "Message version (0x00 for this version)"

[[CFG-PMS.fields]]
format = "U1"
name = "powerSetupValue"
doc = "Power setup value"


[CFG-PMS.fields.map]
0 = "Full power"
1 = "Balanced"
2 = "Interval"
3 = "Aggressive with 1 Hz"
4 = "Aggressive with 2 Hz"
5 = "Aggressive with 4 Hz"
255 = "Invalid (only when polling)"

[[CFG-PMS.fields]]
format = "U2"
name = "period"
unit = "s"
doc = """
Position update period and search period.
Recommended minimum period is 10 s,
although the receiver accepts any value
bigger than 5 s.\n
Only valid when powerSetupValue set to
Interval, otherwise must be set to '0'.
"""

[[CFG-PMS.fields]]
format = "U2"
name = "onTime"
unit = "s"
doc = """
Duration of the ON phase, must be smaller
than the period.
Only valid when powerSetupValue set to
Interval, otherwise must be set to '0'.
Reserved
"""

[[CFG-PMS.fields]]
format = "U1[2]"
name = "reserved1"


[MON-VER]
clsID = 10
msgID = 4

[[MON-VER.fields]]
format = "CH[30]"
name = "swVersion"

[[MON-VER.fields]]
format = "CH[10]"
name = "hwVersion"

[[MON-VER.fields]]
format = "CH[30]"
name = "extension"
repeat = true


[NAV-PVT]
clsID = 1
msgID = 7

[[NAV-PVT.fields]]
format = "U4"
name = "iTOW"
unit = "ms"
doc = "GPS time of week of the navigation epoch."

[[NAV-PVT.fields]]
format = "U2"
name = "year"
unit = "y"
doc = "Year (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "month"
unit = "month"
doc = "Month, range 1..12 (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "day"
unit = "d"
doc = "Day of month, range 1..31 (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "hour"
unit = "h"
doc = "Hour of day, range 0..23 (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "min"
unit = "min"
doc = "Minute of hour, range 0..59 (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "sec"
unit = "s"
doc = "Seconds of minute, range 0..60 (UTC)"

[[NAV-PVT.fields]]
format = "X1"
name = "valid"
doc = "-,Validity flags (see graphic below)"
bitfield = []

[[NAV-PVT.fields]]
format = "U4"
name = "tAcc"
unit = "ns"
doc = "Time accuracy estimate (UTC)"

[[NAV-PVT.fields]]
format = "I4"
name = "nano"
unit = "ns"
doc = "Fraction of second, range -1e9 .. 1e9 (UTC)"

[[NAV-PVT.fields]]
format = "U1"
name = "fixType"
doc = "-,GNSSfix Type:"


[NAV-PVT.fields.map]
0 = "no fix"
1 = "dead reckoning only"
2 = "2D-fix"
3 = "3D-fix"
4 = "GNSS + dead reckoning combined"
5 = "time only fix"

[[NAV-PVT.fields]]
format = "X1"
name = "flags"
doc = "-,Fix status flags (see graphic below)"
bitfield = []

[[NAV-PVT.fields]]
format = "X1"
name = "flags2"
doc = "-,Additional flags (see graphic below)"
bitfield = []

[[NAV-PVT.fields]]
format = "U1"
name = "numSV"
unit = "-"
doc = "Number of satellites used in Nav Solution"

[[NAV-PVT.fields]]
format = "I4"
name = "lon"
unit = "deg"
doc = "Longitude"

[[NAV-PVT.fields]]
format = "I4"
name = "lat"
unit = "deg"
doc = "Latitude"

[[NAV-PVT.fields]]
format = "I4"
name = "height"
unit = "mm"
doc = "Height above ellipsoid"

[[NAV-PVT.fields]]
format = "I4"
name = "hMSL"
unit = "mm"
doc = "Height above mean sea level"

[[NAV-PVT.fields]]
format = "U4"
name = "hAcc"
unit = "mm"
doc = "Horizontal accuracy estimate"

[[NAV-PVT.fields]]
format = "U4"
name = "vAcc"
unit = "mm"
doc = "Vertical accuracy estimate"

[[NAV-PVT.fields]]
format = "I4"
name = "velN"
doc = "mm/s,NED north velocity"

[[NAV-PVT.fields]]
format = "I4"
name = "velE"
doc = "mm/s,NED east velocity"

[[NAV-PVT.fields]]
format = "I4"
name = "velD"
doc = "mm/s,NED down velocity"

[[NAV-PVT.fields]]
format = "I4"
name = "gSpeed"
doc = "mm/s,Ground Speed (2-D)"

[[NAV-PVT.fields]]
format = "I4"
name = "headMot"
unit = "deg"
doc = "Heading of motion (2-D,)"

[[NAV-PVT.fields]]
format = "U4"
name = "sAcc"
doc = "mm/s,Speed accuracy estimate"

[[NAV-PVT.fields]]
format = "U4"
name = "headAcc"
unit = "deg"
doc = "Heading accuracy estimate (both motion and vehicle)"

[[NAV-PVT.fields]]
format = "U2"
name = "pDOP"
doc = "-,Position DOP"

[[NAV-PVT.fields]]
format = "X1"
name = "flags3"
doc = "-,Additional flags (see graphic below)"
bitfield = []

[[NAV-PVT.fields]]
format = "U1[5]"
name = "reserved1"
doc = "-,Reserved"

[[NAV-PVT.fields]]
format = "I4"
name = "headVeh"
unit = "deg"
doc = """\
Heading of vehicle (2-D), this is only valid when headVehValid is set,
otherwise the output is set to the heading of motion
"""

[[NAV-PVT.fields]]
format = "I2"
name = "magDec"
unit = "deg"
doc = "Magnetic declination. Only supported in ADR 4.10 and later."

[[NAV-PVT.fields]]
format = "U2"
name = "magAcc"
doc = "1e-2,Magnetic declination accuracy. Only supported in ADR 4.10 and later."


[NAV-POSLLH]
clsID = 1
msgID = 2

[[NAV-POSLLH.fields]]
format = "U4"
name = "iTOW"
unit = "ms"
doc = "GPS time of week of the navigation epoch. See the description of iTOW for details."

[[NAV-POSLLH.fields]]
format = "I4"
name = "lon"
unit = "deg"
doc = "Longitude"

[[NAV-POSLLH.fields]]
format = "I4"
name = "lat"
unit = "deg"
doc = "Latitude"

[[NAV-POSLLH.fields]]
format = "I4"
name = "height"
unit = "mm"
doc = "Height above ellipsoid"

[[NAV-POSLLH.fields]]
format = "I4"
name = "hMSL"
unit = "mm"
doc = "Height above mean sea level"

[[NAV-POSLLH.fields]]
format = "U4"
name = "hAcc"
unit = "mm"
doc = "Horizontal accuracy estimate"

[[NAV-POSLLH.fields]]
format = "U4"
name = "vAcc"
unit = "mm"
doc = "Vertical accuracy estimate"

# CFG-NAV5

[CFG-NAV5]
clsID = 6
msgID = 36

[[CFG-NAV5.fields]]
format = "X2"
name = "mask"

[[CFG-NAV5.fields.bitfield]]
range = 0
name = "dyn"
doc = "Apply dynamic model settings"

[[CFG-NAV5.fields.bitfield]]
range = 1
name = "minEl"
doc = "Apply minimum elevation settings"

[[CFG-NAV5.fields.bitfield]]
range = 2
name = "posFixMode"
doc = "Apply fix mode settings"

[[CFG-NAV5.fields.bitfield]]
range = 3
name = "drLim"
doc = "Reserved"

[[CFG-NAV5.fields.bitfield]]
range = 4
name = "posMask"
doc = "Apply position mask settings"

[[CFG-NAV5.fields.bitfield]]
range = 5
name = "timeMask"
doc = "Apply time mask settings"

[[CFG-NAV5.fields.bitfield]]
range = 6
name = "staticHoldMask"
doc = "Apply static hold settings"

[[CFG-NAV5.fields.bitfield]]
range = 7
name = "dgpsMask"
doc = "Apply DGPS settings"

[[CFG-NAV5.fields.bitfield]]
range = 8
name = "cnoThreshold"
doc = "Apply CNO threshold settings (cnoThresh, cnoThreshNumSVs)"

[[CFG-NAV5.fields.bitfield]]
range = 10
name = "uct"
doc = "Apply UTC settings"

[[CFG-NAV5.fields]]
format = "U1"
name = "dynModel"

[CFG-NAV5.fields.map]
0 = "portable"
2 = "stationary"
3 = "pedestrian"
4 = "automotive"
5 = "sea"
6 = "airborne with <1g acceleration"
7 = "airborne with <2g acceleration"
8 = "airborne with <4g acceleration"
9 = "wrist-worn watch (not supported in protocol versions less than 18)"
10 = "bike (supported in protocol versions 19.)"

[[CFG-NAV5.fields]]
format = "U1"
name = "fixMode"

[CFG-NAV5.fields.map]
1 = "2D only"
2 = "3D only"
3 = "auto 2D/3D"

[[CFG-NAV5.fields]]
format = "I4"
name = "fixedAlt"

[[CFG-NAV5.fields]]
format = "U4"
name = "fixedAltVar"

[[CFG-NAV5.fields]]
format = "I1"
name = "minElev"

[[CFG-NAV5.fields]]
format = "U1"
name = "drLimit"

[[CFG-NAV5.fields]]
format = "U2"
name = "pDop"

[[CFG-NAV5.fields]]
format = "U2"
name = "tDop"

[[CFG-NAV5.fields]]
format = "U2"
name = "pAcc"

[[CFG-NAV5.fields]]
format = "U2"
name = "tAcc"

[[CFG-NAV5.fields]]
format = "U1"
name = "staticHoldThr"

[[CFG-NAV5.fields]]
format = "U1"
name = "dgnssTimeout"

[[CFG-NAV5.fields]]
format = "U1"
name = "cnoThreshNumS"

[[CFG-NAV5.fields]]
format = "U1"
name = "cnoThresh"

[[CFG-NAV5.fields]]
format = "U1[2]"
name = "reserved1"

[[CFG-NAV5.fields]]
format = "U2"
name = "staticHoldMax"

[[CFG-NAV5.fields]]
format = "U1"
name = "utcStandard"

[CFG-NAV5.fields.map]
0 = "Automatic; receiver selects based on; GNSS configuration (see GNSS time; bases)"
3 = "UTC as operated by the U.S. Naval; Observatory (USNO); derived from GPS time"
5 = "UTC as combined from multiple European laboratories; derived from Galileo time"
6 = "UTC as operated by the former Soviet; Union (SU); derived from GLONASS time"
7 = "UTC as operated by the National Time; Service Center (NTSC), China; derived from BeiDou time; (not supported in protocol versions less than 16)."

[[CFG-NAV5.fields]]
format = "U1[5]"
name = "reserved2"

# CFG-PRT

[CFG-PRT]
clsID = 6
msgID = 0

[[CFG-PRT.fields]]
format = "U1"
name = "portID"
doc = "Port identifier number (see Integration ,manual for valid UART port IDs)"

[[CFG-PRT.fields]]
format = "U1"
name = "reserved1"
doc = "Reserved Byte Offset"

[[CFG-PRT.fields]]
format = "X2"
name = "txReady"
doc = "TX ready PIN configuration (see graphic below)"

[[CFG-PRT.fields.bitfield]]
name = "en"
range = 0
doc = "Enable TX ready feature for this port"

[[CFG-PRT.fields.bitfield]]
name = "pol"
range = 1
doc = "Polarity 0 High-active 1 Low-active"

[[CFG-PRT.fields.bitfield]]
name = "pin"
range = 6
doc = "PIO to be used (must not be in use by another function)"

[[CFG-PRT.fields.bitfield]]
name = "thres"
range = 15
doc = "Threshold The given threshold is multiplied by 8 bytes. The TX ready PIN goes active after >= thres*8 bytes are pending for the port and going inactive after the last pending bytes have been written to hardware (0-4 bytes before end of stream). 0x000 no threshold 0x001 8byte 0x002 16byte ... 0x1FE 4080byte 0x1FF 4088byte"

[[CFG-PRT.fields]]
format = "X4"
name = "mode"
doc = "A bit mask describing the UART mode (see graphic below)"

[[CFG-PRT.fields.bitfield]]
name = "charLen"
range = [ 7, 6,]
doc = "Character length"


[CFG-PRT.fields.bitfield.map]
0 = "5bit (not supported)"
1 = "6bit (not supported)"
2 = "7bit (supported only with parity)"
3 = "8bit"

[[CFG-PRT.fields.bitfield]]
name = "parity"
range = [ 11, 9,]


[CFG-PRT.fields.bitfield.map]
000 = "Even parity"
001 = "Odd parity"
10X = "No parity"
X1X = "Reserved"

[[CFG-PRT.fields.bitfield]]
name = "nStopBits"
range = [ 13, 12,]
doc = "Number of Stop bits"


[CFG-PRT.fields.bitfield.map]
00 = "1 Stop bit"
01 = "1.5 Stop bit"
10 = "2 Stop bit"
11 = "0.5 Stop bit"

[[CFG-PRT.fields]]
format = "U4"
name = "baudRate"
doc = "Bits/s,Baud rate in bits/second"

[[CFG-PRT.fields]]
format = "X2"
name = "inProtoMask"
doc = """\
A mask describing which input protocols are active.
Each bit of this mask is used for a protocol.
Through that, multiple protocols can be defined on a single port.
(see graphic below)
"""

[[CFG-PRT.fields.bitfield]]
name = "inUbx"
range = 0
doc = "UBX protocol"

[[CFG-PRT.fields.bitfield]]
name = "inNmea"
range = 1
doc = "NMEA protocol"

[[CFG-PRT.fields.bitfield]]
name = "inRtcm"
range = 2
doc = "RTCM2 protocol"

[[CFG-PRT.fields.bitfield]]
name = "inRtcm3"
range = 5
doc = "RTCM3 protocol (not supported in protocol versions less than 20)"

[[CFG-PRT.fields]]
format = "X2"
name = "outProtoMask"
doc = """\
A mask describing which output protocols are active.
Each bit of this mask is used for a protocol.
Through that, multiple protocols can be defined on a single port.
(see graphic below)
"""

[[CFG-PRT.fields.bitfield]]
name = "outUbx"
range = 0
doc = "UBX protocol"

[[CFG-PRT.fields.bitfield]]
name = "outNmea"
range = 1
doc = "NMEA protocol"

[[CFG-PRT.fields.bitfield]]
name = "inRtcm3"
range = 5
doc = "RTCM3 protocol (not supported in protocol versions less than 20)"

[[CFG-PRT.fields]]
format = "X2"
name = "flags"

[[CFG-PRT.fields.bitfield]]
name = "extendedTxTimeout"
range = 1

[[CFG-PRT.fields]]
format = "U1[2]"
name = "reserved2"


[CFG-TP5]
clsID = 6
msgID = 49

[[CFG-TP5.fields]]
format = "U1"
name = "tpIdx"

[[CFG-TP5.fields]]
format = "U1"
name = "version"

[[CFG-TP5.fields]]
format = "U1[2]"
name = "reserved1"

[[CFG-TP5.fields]]
format = "I2"
name = "antCableDelay"

[[CFG-TP5.fields]]
format = "I2"
name = "rfGroupDelay"

[[CFG-TP5.fields]]
format = "U4"
name = "freqPeriod"

[[CFG-TP5.fields]]
format = "U4"
name = "freqPeriodLock"

[[CFG-TP5.fields]]
format = "U4"
name = "pulseLenRatio"

[[CFG-TP5.fields]]
format = "U4"
name = "pulseLenRatioLock"

[[CFG-TP5.fields]]
format = "I4"
name = "userConfigDel"

[[CFG-TP5.fields]]
format = "X4"
name = "flags"

[[CFG-TP5.fields.bitfield]]
name = "active"
range = 0

[[CFG-TP5.fields.bitfield]]
name = "lockGpsFreq"
range = 1

[[CFG-TP5.fields.bitfield]]
name = "lockedOtherSet"
range = 2

[[CFG-TP5.fields.bitfield]]
name = "isFreq"
range = 3

[[CFG-TP5.fields.bitfield]]
name = "isLength"
range = 4

[[CFG-TP5.fields.bitfield]]
name = "alignToTow"
range = 5

[[CFG-TP5.fields.bitfield]]
name = "polarity"
range = 6

[[CFG-TP5.fields.bitfield]]
name = "gridUtcGps"
range = 7



[_EXAMPLE]
clsID = 153
msgID = 153

[[_EXAMPLE.fields]]
format = "U1"
name = "portID"
doc = ""

[[_EXAMPLE.fields]]
format = "X2"
name = "outProtoMask"
doc = ""

[[_EXAMPLE.fields.bitfield]]
name = "outUbx"
range = 0
doc = ""
